/**
 * RigStateTest.jsx — Micro States Layer Viewer
 * Embeds the Plotly QC layer visualization generated by viz_micro_state_layers.py
 */
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';

const WELLS = [
  { licence: '0516486', label: '0516486' },
];

export default function RigStateTest() {
  const navigate = useNavigate();
  const [selectedWell, setSelectedWell] = useState(WELLS[0].licence);

  const src = `/micro_state_layers_${selectedWell}.html`;

  return (
    <div style={{ height: '100vh', display: 'flex', flexDirection: 'column', background: '#1a1a2e' }}>
      {/* Thin header bar */}
      <div style={{ display: 'flex', alignItems: 'center', gap: '12px', padding: '8px 16px', borderBottom: '1px solid #333', background: '#0f0f23', flexShrink: 0 }}>
        <button onClick={() => navigate(-1)} style={{ background: 'none', border: '1px solid #444', borderRadius: '4px', cursor: 'pointer', color: '#ccc', fontSize: '14px', padding: '2px 8px' }}>&larr;</button>
        <span style={{ fontSize: '14px', fontWeight: 600, color: '#e0e0e0' }}>Micro State Layers</span>
        <select
          value={selectedWell}
          onChange={(e) => setSelectedWell(e.target.value)}
          style={{ padding: '4px 8px', background: '#1e293b', border: '1px solid #444', borderRadius: '4px', color: '#e0e0e0', fontSize: '13px' }}
        >
          {WELLS.map(w => (
            <option key={w.licence} value={w.licence}>{w.label}</option>
          ))}
        </select>
      </div>
      {/* Full-page iframe */}
      <iframe
        src={src}
        style={{ flex: 1, border: 'none', width: '100%' }}
        title="Micro State Layers"
      />
    </div>
  );
}
